spring:
  application:
    name: authentication-service

server:
  port: 8080

com.example:
  user-resource:
    location: http://user-resource-service:8080
  jwt-resource:
    location: http://jwt-resource-service:8080
  acl-resource:
    location: http://acl-resource-service:8080
